// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.meplayer.scouting;

import com.meplayer.scouting.Agente;

privileged aspect Agente_Roo_JavaBean {
    
    public String Agente.getNombre() {
        return this.nombre;
    }
    
    public void Agente.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String Agente.getApellidos() {
        return this.apellidos;
    }
    
    public void Agente.setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    public String Agente.getMail() {
        return this.mail;
    }
    
    public void Agente.setMail(String mail) {
        this.mail = mail;
    }
    
    public String Agente.getTelf_movil() {
        return this.telf_movil;
    }
    
    public void Agente.setTelf_movil(String telf_movil) {
        this.telf_movil = telf_movil;
    }
    
    public String Agente.getTelf_fijo() {
        return this.telf_fijo;
    }
    
    public void Agente.setTelf_fijo(String telf_fijo) {
        this.telf_fijo = telf_fijo;
    }
    
    public String Agente.getDireccion() {
        return this.direccion;
    }
    
    public void Agente.setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    public String Agente.getNum_licencia() {
        return this.num_licencia;
    }
    
    public void Agente.setNum_licencia(String num_licencia) {
        this.num_licencia = num_licencia;
    }
    
}
