// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.meplayer.scouting;

import com.meplayer.scouting.Agente;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Agente_Roo_Configurable {
    
    declare @type: Agente: @Configurable;
    
}
