// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.meplayer.scouting;

import com.meplayer.scouting.Agente;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Agente_Roo_Jpa_Entity {
    
    declare @type: Agente: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Agente.id;
    
    @Version
    @Column(name = "version")
    private Integer Agente.version;
    
    public Long Agente.getId() {
        return this.id;
    }
    
    public void Agente.setId(Long id) {
        this.id = id;
    }
    
    public Integer Agente.getVersion() {
        return this.version;
    }
    
    public void Agente.setVersion(Integer version) {
        this.version = version;
    }
    
}
